name: Test

on:
  workflow_dispatch:
  schedule:
    # Runs at 8 AM, 2 PM, and 8 PM UTC daily (adjust timing as needed)
    - cron: '0 8,14,20 * * *'

jobs:
  increase-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm-increaser-downloads
        run: npm install -g npm-increaser-downloads

      - name: Define packages dynamically
        run: |
          PACKAGES=(
            "react-theme-switch-animation"
            "react-native-converted-in-sdk"
            "npm-increaser-downloads"
          )

          # Export the packages as a comma-separated string
          echo "PACKAGES=${PACKAGES[*]}" >> $GITHUB_ENV

      - name: Run Increase Downloads for each package
        run: |
          # Read the packages from the environment variable
          IFS=',' read -r -a PACKAGE_LIST <<< "$PACKAGES"

          # Loop through each package and run the increase downloads command
          for PACKAGE in "${PACKAGE_LIST[@]}"; do
            # Generate random number of downloads between 55 and 155 for each package
            RANDOM_DOWNLOADS=$((1000 + RANDOM % 2000))

            # Run the command with the generated random number of downloads
            nid --package-name "$PACKAGE" --num-downloads $RANDOM_DOWNLOADS --max-concurrent-downloads 300 --download-timeout 3000

            echo "Processed $PACKAGE with $RANDOM_DOWNLOADS downloads"
          done
